version: '3.8'
services:
  dev-payment-service-provider-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest-bookmark
    networks:
      - psp-net
networks:
  psp-net: